### ISSUE TITLE
about the some stream files

### ISSUE THREAD

**Issue by elasticheartt** [segabl/pd2-soundbank-editor#1]
Like you had mentioned wwise_ima_adpcm.exe really can't convert all of stream files. I was wondering if there's a way to convert them to wav format too? Since I couldn't find any related guide or tool for it.

**Comment by segabl** [comment]
i think you need a specific version of the full wwise software that can read them and lets you convert them but I don't know any specifics.

**Comment by elasticheartt** [comment]
I did download an older build of wwise and tried it but. Since mine are still in .stream format and not wav. idk how to process any further than that.

**Comment by segabl** [comment]
I'm not sure what exactly the necessary steps are, you might find help on the MWS discord since there are a few people there that have done it before
